version: '3'
services:
  proxy:
    image: traefik:latest
    tty: true
    ports:
      - '127.0.0.1:8080:80'
    volumes:
      - './traefik.yml:/etc/traefik/traefik.yml:ro'
      - './routes.yml:/etc/traefik/routes.yml:ro'
  redis:
    image: redis:latest
    tty: true
  bank:
    build:
      context: .
      dockerfile: generic.Dockerfile
    image: ouspg/seceng-generic:latest
    tty: true
    volumes:
      - './bank.py:/opt/server/server.py:ro'
    environment:
      - 'BASE_URL=bank.ouspg.org.localhost'
  analytics:
    build:
      context: .
      dockerfile: generic.Dockerfile
    image: ouspg/seceng-generic:latest
    tty: true
    volumes:
      - './analytics.py:/opt/server/server.py:ro'
  command:
    build:
      context: .
      dockerfile: generic.Dockerfile
    image: ouspg/seceng-generic:latest
    tty: true
    volumes:
      - './command.py:/opt/server/server.py:ro'
  user:
    build:
      context: .
      dockerfile: generic.Dockerfile
    image: ouspg/seceng-generic:latest
    tty: true
    volumes:
      - './create_your_server.py:/opt/server/server.py:ro'