http:
  routers:
    to-bank:
      rule: Host(`bank.ouspg.org.localhost`)
      service: bank
    to-analytics:
      rule: Host(`analytics.bank.ouspg.org.localhost`)
      service: analytics
    to-command:
      rule: "Host(`hosting-provider.org.localhost`) && PathPrefix(`/servers`)"
      service: command
  services:
    bank:
      loadBalancer:
        servers:
          - url: http://bank/
    analytics:
      loadBalancer:
        servers:
          - url: http://analytics/
    command:
      loadBalancer:
        servers:
          - url: http://command/